### ISSUE TITLE
Update for Bootstrap 4

### ISSUE THREAD

**Issue by donv** [bfcoder/bootstrap-chosen-rails#2]
Hi!

The variables have changed in Bootstrap 4.  The API for Bootstrap 4 is now stable, so an update of this gem would be welcome.

**Comment by bfcoder** [comment]
Alas, I'm not the one that made the bootstrap integration. That was all done in [https://github.com/alxlit/bootstrap-chosen](https://github.com/alxlit/bootstrap-chosen). I only ported what that guy did to the rails asset pipeline. Once he updates, then I'll grab the new styles and update. Sorry. :/
